devices:
  1:
    acceleration: 10000
    backoff volume: 500
    class: PSD4_smooth
    default init rate: 200
    default rate: 50
    name: Reservoir cell inlet 1
    return volume: 0
    start rate: 20
    stop rate: 20
    syringevolume: 12500
    type: PSD
    valve alias:
      1: Cell
      2: Waste
      3: open
    valve type: 3-way 90 degree distribution valve
  2:
    acceleration: 10000
    backoff volume: 500
    class: PSD4_smooth
    default init rate: 200
    default rate: 50
    name: Cell outlet 1
    return volume: 0
    start rate: 20
    stop rate: 20
    syringevolume: 12500
    type: PSD
    valve alias:
      1: Reservoir
      2: Waste
      3: Cell
    valve type: 3-way 90 degree distribution valve
  3:
    acceleration: 10000
    backoff volume: 500
    class: PSD4_smooth
    default init rate: 200
    default rate: 50
    name: Reservoir cell inlet 2
    return volume: 0
    start rate: 20
    stop rate: 20
    syringevolume: 12500
    type: PSD
    valve alias:
      1: Cell
      2: Waste
      3: open
    valve type: 3-way 90 degree distribution valve
  4:
    acceleration: 10000
    backoff volume: 1000
    class: PSD4_smooth
    default init rate: 200
    default rate: 50
    name: Cell outlet 2
    return volume: 0
    start rate: 20
    stop rate: 20
    syringevolume: 12500
    type: PSD
    valve alias:
      1: Reservoir
      2: Waste
      3: Cell
    valve type: 3-way 90 degree distribution valve
  5:
    class: Valve
    name: Distribution valve
    type: MVP
    valve alias:
      1: Reservoir cell inlet 1
      2: Reservoir cell inlet 2
      3: Cell outlet 1
      4: Cell outlet 2
    valve type: 4-way 90 degree valve
operations:
  ExchangePair:
    Exchanger 1:
      args:
      - Syringe 4
      - Syringe 3
      bubbleDispense: 500
      defaultDrainRate: 400
      defaultFillRate: 400
      defaultRate: 60
      dispenseDelay: 0.0
      prePressure: 0
      prePressureRate: 60
      pullSyr:
        Cell: Cell
        Waste: Waste
      pushSyr:
        Cell: Cell
        Reservoir: Reservoir
        Waste: Waste
      underPressure: 50
      underPressureRate: 60
    Exchanger 2:
      args:
      - Syringe 2
      - Syringe 1
      bubbleDispense: 500
      defaultDrainRate: 400
      defaultFillRate: 400
      defaultRate: 60
      dispenseDelay: 0.0
      prePressure: 0
      prePressureRate: 60
      pullSyr:
        Cell: Cell
        Waste: Waste
      pushSyr:
        Cell: Cell
        Reservoir: Reservoir
        Waste: Waste
      underPressure: 50
      underPressureRate: 60
psd_widget:
  S1_S3_pull_syringe_id: 4
  S2_S4_pull_syringe_id: 1
  cell_vol: 0
  connect_status:
    1: disconnected
    2: disconnected
    3: disconnected
    4: disconnected
    mvp: disconnected
  filling_status:
    1: true
    2: false
    3: true
    4: false
  init_motion_stage: false
  mvp_valve: 1
  operation_mode: not_ready_mode
  prepressure_S1_ready: false
  prepressure_S2_ready: false
  resevoir_vol: 250
  resume_advance_exchange: false
  times_prepresssure_S1: 0
  times_prepresssure_S2: 0
  waste_vol: 0
server:
  database: true
  host: hasep25lab01
  name: test/pumpserver/1
  port: 10000
  serialport: /dev/ttyUSB0
  tangoname: test/pumpserver/1
