Camaras:
  camaraDataFormatCallbacks:
  - lambda data:data[0]
  - lambda data:data.reshape((2048, 2048, 3))
  - lambda data:np.rot90(data, 3)
  camaraDevice: tango://hasp029rack.desy.de:10000/p06/tangovimba/test.01
  camaraStreamModel: tango://hasp029rack.desy.de:10000/p06/tangovimba/test.01/imageraw
  gridLayoutWidgetName: gridLayout_cam
  pixel_size: tango://hasp029rack.desy.de:10000/p06/mscope/lab.01/pixelsize
  presetZoom:
  - 60
  - 80
  - 100
  viewerWidgetName: camara_widget
FileManager:
  currentImageDatabaseDir: C:\\Users\\_admin\\Downloads\\monitor_test
  currentimagedbDir: C:/Users/qiucanro/Downloads
  restoreimagedb: C:\\Users\\qiucanro\\apps\\imgReg\\imgReg\\ImageBackup.imagedb
General:
  ScaleColor: null
  ScaleFontSize: 10
  ScaleHeight: 90
  ScalePosition: Bottom Right
  ScaleSize: 1000
  beamlinePCHostName: hasm5570cq
Motors:
  mot01: motor/motctrl01/1
  mot02: motor/motctrl02/1
  mot03: motor/motctrl02/2
  mot04: motor/motctrl02/3
  mot05: motor/motctrl02/4
Mscope:
  comboBox_illum_types: tango://hasp029rack.desy.de:10000/p06/beamlinemicroscopeillumination/test.01/AvailableIlluminationTypes
  label_illum_pos: tango://hasp029rack.desy.de:10000/p06/beamlinemicroscopeillumination/test.01/intensity{}
PrimBeamGeo:
  img_x: -1472.906730073101
  img_y: -2547.8777032887797
  iso_h: -1696.0795454545457
  iso_v: -413.65056818181824
  stage_x: -9.100312499999998
  stage_y: -37.31375
QueueControl:
  ntp_host: haspp06deb10
  ntp_port: 13345
SampleStages:
  label_x_stage_value: tango://hasp029rack.desy.de:10000/p06/motor/exp.02/position
  label_y_stage_value: tango://hasp029rack.desy.de:10000/p06/motor/exp.01/position
  label_z_stage_value: tango://hasp029rack.desy.de:10000/motor/dummy_mot_ctrl/3/position
  label_zoom_pos: tango://hasp029rack.desy.de:10000/p06/mscope/lab.01/zoom
Visuals:
  boxColor: null
  boxLinewidth: 2
  showBox: 1
  showScalebar: 0
widgetMaps:
  beamlineControlGpNames: SampleStages
