Camaras:
  camaraDataFormatCallbacks:
  - lambda data:np.rot90(data,3)
  camaraDevice: tango://hasp029rack.desy.de:10000/p06/tangovimba/test.01
  camaraExposure_mode:
    attr_name: ExposureAuto
    options:
    - 'Off'
    - Once
    - Continuous
  camaraExposure_time:
    attr_name: ExposureTimeAbs
    default_value: null
  camaraStreamModel: tango://hasp029rack.desy.de:10000/p06/tangovimba/test.01/image8
  click_move_timeout: 120
  gridLayoutWidgetName: gridLayout_cam
  pixel_size: tango://hasp029rack.desy.de:10000/p06/mscope/lab.01/pixelsize
  presetZoom:
  - 60
  - 80
  - 100
  rgb: false
  viewerWidgetName: camara_widget
FileManager:
  currentImageDatabaseDir: C:\\Users\\_admin\\Downloads\\monitor_test
  currentimagedbDir: C:/Users/qiucanro/Downloads
  restoreimagedb: C:\\Users\\qiucanro\\apps\\imgReg\\imgReg\\ImageBackup.imagedb
General:
  ScaleColor: null
  ScaleFontSize: 10
  ScaleHeight: 90
  ScalePosition: Bottom Right
  ScaleSize: 1000
  beamlinePCHostName: hasm5570cq
Motors:
  samly: tango://hasp029rack.desy.de:10000/p06/motor/exp.02
  samlz: tango://hasp029rack.desy.de:10000/p06/motor/exp.01
Mscope:
  comboBox_illum_types: tango://hasp029rack.desy.de:10000/p06/beamlinemicroscopeillumination/test.01/AvailableIlluminationTypes
  label_illum_pos: tango://hasp029rack.desy.de:10000/p06/beamlinemicroscopeillumination/test.01/intensity{}
PrimBeamGeo:
  img_x: -1443.021826817273
  img_y: -2339.9093239048266
  iso_h: -1363.6363636363637
  iso_v: -454.5454545454544
  stage_x: -9.999999999999996
  stage_y: -30.0
QueueControl:
  ntp_host: haspp06deb10
  ntp_port: 13345
SampleStageMotorNames:
  x: samly
  y: samlz
  z: samlx
SampleStages:
  x_stage_value: tango://hasp029rack.desy.de:10000/p06/motor/exp.02/position
  y_stage_value: tango://hasp029rack.desy.de:10000/p06/motor/exp.01/position
  z_stage_value: tango://hasp029rack.desy.de:10000/motor/dummy_mot_ctrl/3/position
Visuals:
  boxColor: null
  boxLinewidth: 2
  showBox: 1
  showScalebar: 0
spockLogin:
  doorAlias: Door-hasp029rack
  doorName: tango://hasp029rack.desy.de:10000/p06/door/hasp029rack.01
  msAlias: MS-hasp029rack
  msName: tango://hasp029rack.desy.de:10000/p06/macroserver/hasp029rack.01
synopticViewer:
  camera_sources:
  - model: tango://hasp029rack:10000/sys/tg_test/1/uchar_image_ro
    type: 2D
  - model: tango://hasp029rack:10000/sys/tg_test/1/ulong64_image_ro
    type: 2D
  - model: tango://hasp029rack:10000/sys/tg_test/1/short_image_ro
    type: 2D
widgetMaps:
  beamlineControlGpNames: SampleStages
