Camaras:
  camaraDataFormatCallbacks:
  - lambda data:np.rot90(data[0].reshape((2048,2048,3)),3)
  camaraDevice: tango://hasp029rack.desy.de:10000/p06/tangovimba/test.01
  camaraExposure_mode:
    attr_name: ExposureAuto
    options:
    - false
    - Once
    - Continuous
  camaraExposure_time:
    attr_name: ExposureTimeAbs
    default_value: None
  camaraStreamModel: tango://hasp029rack.desy.de:10000/p06/tangovimba/test.01/imageRaw
  click_move_timeout: 120
  exported_image_folder: C://Users//qiucanro//Downloads
  gridLayoutWidgetName: gridLayout_cam
  pixel_size: tango://hasp029rack.desy.de:10000/p06/mscope/lab.01/pixelsize
  presetZoom:
  - 60
  - 80
  - 100
  rgb: true
  viewerWidgetName: camara_widget
FileManager:
  currentImageDatabaseDir: C:\\Users\\_admin\\Downloads\\monitor_test
  currentimagedbDir: C://Users//qiucanro//Downloads
  restoreimagedb: C:\\Users\\qiucanro\\apps\\imgReg\\imgReg\\ImageBackup.imagedb
General:
  ScaleColor: ''
  ScaleFontSize: 10
  ScaleHeight: 90
  ScalePosition: Bottom Right
  ScaleSize: 1000
  beamlinePCHostName: hasm5570cq
  connect_model_startup: true
  darkstyle: false
  db: tango://hasp029rack.desy.de:10000
Motors:
  exp_mot03: tango://hasp029rack.desy.de:10000/p06/motor/exp.03
  exp_mot04: tango://hasp029rack.desy.de:10000/p06/motor/exp.04
  samly: tango://hasp029rack.desy.de:10000/p06/motor/exp.02
  samlz: tango://hasp029rack.desy.de:10000/p06/motor/exp.01
Mscope:
  comboBox_illum_types: tango://hasp029rack.desy.de:10000/p06/beamlinemicroscopeillumination/test.01/AvailableIlluminationTypes
  label_illum_pos: tango://hasp029rack.desy.de:10000/p06/beamlinemicroscopeillumination/test.01/intensity{}
PrimBeamGeo:
  img_x: -793.7578029843893
  img_y: -1518.9188027885748
  iso_h: -340.44012063889625
  iso_v: 233.45525568181813
  stage_x: 5.136015624999999
  stage_y: -11.000156249999975
QueueControl:
  ntp_host: haspp06deb10
  ntp_port: 13345
SampleStageMotorNames:
  scanx: samly
  scany: samlz
  scanz: exp_dmy03
  x: samly
  y: samlz
  z: exp_dmy03
SampleStages:
  x_pstage_value: tango://hasp029rack.desy.de:10000/p06/motor/exp.02/position
  x_stage_value: tango://hasp029rack.desy.de:10000/p06/motor/exp.02/position
  y_pstage_value: tango://hasp029rack.desy.de:10000/p06/motor/exp.01/position
  y_stage_value: tango://hasp029rack.desy.de:10000/p06/motor/exp.01/position
  z_pstage_value: tango://hasp029rack.desy.de:10000/motor/dummy_mot_ctrl/3/position
  z_stage_value: tango://hasp029rack.desy.de:10000/motor/dummy_mot_ctrl/3/position
ScanType:
  two_set_of_stage: false
TaurusMotors:
  piezo_stage:
    piezo_stage_x: tango://hasp029rack.desy.de:10000/p06/motor/exp.02
    piezo_stage_y: tango://hasp029rack.desy.de:10000/p06/motor/exp.01
  possible_styles:
  - read
  - write
  sample_stage1:
    sample_stage_x: tango://hasp029rack.desy.de:10000/p06/motor/exp.02
    sample_stage_y: tango://hasp029rack.desy.de:10000/p06/motor/exp.01
  use_style: write
Visuals:
  boxColor: (200, 200, 0)
  boxLinewidth: 2
  showBox: 1
  showScalebar: 0
ZoomDevice:
  label_zoom_pos: tango://hasp029rack.desy.de:10000/p06/mscope/lab.01/zoom
motor_alias_address_map:
  exp_mot03: tango://hasp029rack.desy.de:10000/p06/motor/exp.03
  samlx: tango://hasp029rack.desy.de:10000/motor/dummy_mot_ctrl/3
  samly: tango://hasp029rack.desy.de:10000/p06/motor/exp.02
  samlz: tango://hasp029rack.desy.de:10000/p06/motor/exp.01
spockLogin:
  doorAlias: Door-hasp029rack
  doorName: tango://hasp029rack.desy.de:10000/p06/door/hasp029rack.01
  msAlias: MS-hasp029rack
  msName: tango://hasp029rack.desy.de:10000/p06/macroserver/hasp029rack.01
  useQTSpock: true
synopticViewer:
  camera_sources:
  - model: tango://hasp029rack:10000/sys/tg_test/1/uchar_image_ro
    type: 2D
  - model: tango://hasp029rack:10000/sys/tg_test/1/ulong64_image_ro
    type: 2D
  - model: tango://hasp029rack:10000/sys/tg_test/1/short_image_ro
    type: 2D
viewerTabWidgetVisibility:
  CameraStream:
    index: 0
    show: true
  SardanaSequencer:
    index: 1
    show: false
  configEditor:
    index: 10
    show: true
  imageReg:
    index: 9
    show: true
  motorViewer:
    index: 4
    show: false
  onlineMonitor:
    index: 3
    show: false
  scanQueue:
    index: 2
    show: true
  synopticViewer:
    index: 5
    show: true
  taurus1DPlot:
    index: 7
    show: true
  taurus2DPlot:
    index: 8
    show: true
  taurusMotorViewer:
    index: 6
    show: true
widgetMaps:
  beamlineControlGpNames:
  - SampleStages
  - ZoomDevice
