Camaras:
  camaraDataFormatCallbacks:
  - lambda data:np.rot90(data[0].reshape((2048,2048,3)),3)
  camaraDevice: tango://hasp029rack.desy.de:10000/p06/tangovimba/test.01
  camaraStreamModel: tango://hasp029rack.desy.de:10000/p06/tangovimba/test.01/imageraw
  gridLayoutWidgetName: gridLayout_cam
  pixel_size: tango://hasp029rack.desy.de:10000/p06/mscope/lab.01/pixelsize
  presetZoom:
  - 60
  - 80
  - 100
  viewerWidgetName: camara_widget
FileManager:
  currentImageDatabaseDir: C:\\Users\\_admin\\Downloads\\monitor_test
  currentimagedbDir: C:/Users/qiucanro/Desktop/img_reg/poster
  restoreimagedb: C:\\Users\\qiucanro\\apps\\imgReg\\imgReg\\ImageBackup.imagedb
General:
  ScaleColor: null
  ScaleFontSize: 10
  ScaleHeight: 90
  ScalePosition: Bottom Right
  ScaleSize: 1000
  beamlinePCHostName: hasm5570cq
Motors:
  samly: tango://hasp029rack.desy.de:10000/p06/motor/exp.02
  samlz: tango://hasp029rack.desy.de:10000/p06/motor/exp.01
Mscope:
  comboBox_illum_types: tango://hasp029rack.desy.de:10000/p06/beamlinemicroscopeillumination/test.01/AvailableIlluminationTypes
  label_illum_pos: tango://hasp029rack.desy.de:10000/p06/beamlinemicroscopeillumination/test.01/intensity{}
PrimBeamGeo:
  img_x: -819.4399708750509
  img_y: -2115.327382444797
  iso_h: -1038.181818181817
  iso_v: 239.795809659091
  stage_x: 5.275507812500003
  stage_y: -22.839999999999975
QueueControl:
  ntp_host: haspp06deb10
  ntp_port: 13345
SampleStageMotorNames:
  x: samly
  y: samlz
  z: samlx
SampleStages:
  label_x_stage_value: tango://hasp029rack.desy.de:10000/p06/motor/exp.02/position
  label_y_stage_value: tango://hasp029rack.desy.de:10000/p06/motor/exp.01/position
  label_z_stage_value: tango://hasp029rack.desy.de:10000/motor/dummy_mot_ctrl/3/position
  label_zoom_pos: tango://hasp029rack.desy.de:10000/p06/mscope/lab.01/zoom
Visuals:
  boxColor: null
  boxLinewidth: 2
  showBox: 1
  showScalebar: 0
spockLogin:
  doorAlias: Door-hasp029rack
  doorName: tango://hasp029rack.desy.de:10000/p06/door/hasp029rack.01
  msAlias: MS-hasp029rack
  msName: tango://hasp029rack.desy.de:10000/p06/macroserver/hasp029rack.01
widgetMaps:
  beamlineControlGpNames: SampleStages
