softwareVersion: 0.1.0
basic_shapes:
  rectangle:
    type1:
      dim: [0,0,120,120]
      anchor_pars: null
    type2:
      dim: [0, 0, 80, 40]
      anchor_pars: null
    type3:
      dim: [0, 0, 80, 30]
      anchor_pars: null
    type4:
      dim: [0, 0, 30, 80]
      anchor_pars: null
  circle:
    big:
      dim: [0, 0, 120]
      anchor_pars: null
    small:
      dim: [0, 0, 10]
      anchor_pars: null
    tiny:
      dim: [0, 0, 2]
      anchor_pars: null
  isocelesTriangle:
    type1:
      dim: [0, 0, 40, 60]
      anchor_pars: null
composite_shapes:
  composite1:
    shapes: ['circle.big*1', 'rectangle.type2*4']
    ref_shape: null
    alignment:
      shapes: [[0,1],[0,2],[0,3],[0,4]]
      anchors: [['top','bottom'],['left','right'],['right','left'],['bottom','top']]
      gaps: [0,0,0,0.5]
      ref_anchors: [[null, null],[null, null], [null, null], [null, null]]
    transformation: 
      translate: [100,100]
    models: 
      1: motor/motctrl01/1/position
      2: motor/motctrl02/1/position
      3: motor/motctrl02/2/position
      4: motor/motctrl02/3/position
    callbacks_upon_model_change:
      1: ['callback_model_change_with_transformation', 'mv_dir', 'x']
      2: ['callback_model_change_with_text_label']
      3: ['callback_model_change_with_decoration']
      4: ['callback_model_change_with_transformation', 'mv_dir', 'y']
    callbacks_upon_leftmouse_click:
      1: null
      2: null
      3: null
      4: null
  slit:
    shapes: ['circle.tiny*1', 'rectangle.type3*2', 'rectangle.type4*2']
    ref_shape: null
    hide: [0]
    alignment:
      shapes: [[0,1],[0,2],[0,3],[0,4]]
      anchors: [['top','bottom'],['bottom','top'], ['left','right'],['right','left'],]
      gaps: [0.,0.,0.,0.]
      ref_anchors: [[null, null],[null, null], [null, null], [null, null]]
    transformation: 
      translate: [220,220]
    models: 
      1: motor/motctrl01/1/position
      2: motor/motctrl01/1/position
      3: motor/motctrl02/1/position
      4: motor/motctrl02/1/position
    callbacks_upon_model_change:
      1: 
        - ['callback_model_change_with_transformation', 'mv_dir', 'y', 'sign', '+']
        - ['callback_model_change_with_text_label', 'anchor', 'top']
      2:
        - ['callback_model_change_with_transformation', 'mv_dir', 'y', 'sign', '-']
        - ['callback_model_change_with_text_label', 'anchor', 'bottom']
      3: ['callback_model_change_with_transformation', 'mv_dir', 'x', 'sign', '+']
      4: ['callback_model_change_with_transformation', 'mv_dir', 'x', 'sign', '-']
    callbacks_upon_leftmouse_click:
      1: null
      2: null
      3: null
      4: null      
  valve:
    shapes: ['circle.small*1', 'isocelesTriangle.type1*2']
    ref_shape: null
    hide: []
    alignment:
      shapes: [[0,1],[0,2]]
      anchors: [['left','top'],['right','top']]
      gaps: [0.,0.]
      ref_anchors: [[null, null],[null, null]]
    transformation: 
      translate: [220,220]
    models:
      0: sys/tg_test/1/boolean_scalar
      1: sys/tg_test/1/boolean_scalar
      2: sys/tg_test/1/boolean_scalar
    callbacks_upon_model_change:
      0: ['callback_model_change_with_text_label_on_off', 'anchor', 'top']
      1: ['callback_model_change_with_decoration_on_off']
      2: ['callback_model_change_with_decoration_on_off']
    callbacks_upon_leftmouse_click:
      0: null
      1: null
      2: null
  anchor:
    shapes: ['circle.small*2']
    ref_shape: null
    hide: [0,1]
    alignment:
      shapes: [[0,1]]
      anchors: [['right','left']]
      gaps: [0.]
      ref_anchors: [[null, null]]
    transformation: 
      translate: [220,220]
    models: []
    callbacks_upon_model_change:
      1: []
      2: []
    callbacks_upon_leftmouse_click:
      1: null
      2: null
viewers:
  viewer1:
    composites: ['anchor','valve', 'slit', 'slit', 'valve','slit','anchor']
    transformation:
      translate:
        - [50, 220]
        - [220, 220]
        - [440, 220]
        - [660, 220]
        - [880, 220]
        - [1100, 220]
        - [1300, 220]