softwareVersion: 0.1.0
basic_shapes:
  rectangle:
    type1:
      dim: [0,0,120,120]
      anchor_pars: null
    type2:
      dim: [0, 0, 80, 80]
      anchor_pars: null
      labels:
        text: ['anchor_top_1','anchor_top_4','anchor_bottom_1','anchor_bottom_4','anchor_left_1','anchor_left_4','anchor_right_1','anchor_right_4','center_v','center_h']
        anchor: ['anchor_top_0','anchor_top_3','anchor_bottom_0','anchor_bottom_3','anchor_left_0','anchor_left_3','anchor_right_0','anchor_right_3','center','center']
        orientation: ['horizontal', 'vertical','horizontal', 'vertical','horizontal', 'vertical','horizontal', 'vertical','horizontal', 'vertical']
        decoration: None
    type2b:
      dim: [0, 0, 80, 80]
      anchor_pars: null
      labels:
        text: ['anchor_top_1','anchor_top_2','anchor_top_3','anchor_top_4','anchor_right_1','anchor_right_2','anchor_right_3','anchor_right_4']
        anchor: ['anchor_top_0','anchor_top_1','anchor_top_2','anchor_top_3','anchor_right_0','anchor_right_1','anchor_right_2','anchor_right_3']
        orientation: ['vertical','vertical','vertical','vertical','horizontal', 'horizontal','horizontal','horizontal']
        decoration: None        
    type3:
      dim: [0, 0, 80, 30]
      anchor_pars: null
    type4:
      dim: [0, 0, 30, 80]
      anchor_pars: null
  circle:
    big:
      dim: [0, 0, 120]
      anchor_pars: null
      labels:
        text: ['top','bottom','left','right']
        anchor: ['top','bottom','left','right']
        orientation: ['vertical','vertical','horizontal', 'horizontal']
        decoration: None
    small:
      dim: [0, 0, 60]
      anchor_pars: null
      # labels:
        # text: ['right1','top','right3','bottom','left','right2']
        # anchor: ['right','top','right','bottom','left','right']
        # decoration: None
    tiny:
      dim: [0, 0, 2]
      anchor_pars: null
  isocelesTriangle:
    type1:
      dim: [0, 0, 40, 60]
      anchor_pars: null
      labels:
        text: ['valve']
        anchor: ['bottom']
        orientation: ['horizontal']
        decoration: None
composite_shapes:
  composite1:
    shapes: ['circle.big*1', 'rectangle.type2*4']
    ref_shape: null
    alignment:
      shapes: [[0,1],[0,2],[0,3],[0,4]]
      anchors: [['top','bottom'],['left','right'],['right','left'],['bottom','top']]
      gaps: [0,0,0,0.5]
      ref_anchors: [[null, null],[null, null], [null, null], [null, null]]
    transformation: 
      translate: [100,100]
    models: 
      1: motor/motctrl01/1/position
      2: motor/motctrl02/1/position
      3: motor/motctrl02/2/position
      4: motor/motctrl02/3/position
    callbacks_upon_model_change:
      1: ['callback_model_change_with_transformation', 'mv_dir', 'x']
      2: ['callback_model_change_with_text_label']
      3: ['callback_model_change_with_decoration']
      4: ['callback_model_change_with_transformation', 'mv_dir', 'y']
    callbacks_upon_leftmouse_click:
      1: null
      2: null
      3: null
      4: null
  slit:
    shapes: ['circle.tiny*1', 'rectangle.type3*2', 'rectangle.type4*2']
    ref_shape: null
    hide: [0]
    alignment:
      shapes: [[0,1],[0,2],[0,3],[0,4]]
      anchors: [['top','bottom'],['bottom','top'], ['left','right'],['right','left'],]
      gaps: [0.,0.,0.,0.]
      ref_anchors: [[null, null],[null, null], [null, null], [null, null]]
    transformation: 
      translate: [0,0]
    models: 
      1: motor/motctrl01/1/position
      2: motor/motctrl01/1/position
      3: motor/motctrl02/1/position
      4: motor/motctrl02/1/position
    callbacks_upon_model_change:
      1: 
        - ['callback_model_change_with_transformation', 'mv_dir', 'y', 'sign', '+']
        - ['callback_model_change_with_text_label', 'anchor', 'top', 'orientation','horizontal']
      2:
        - ['callback_model_change_with_transformation', 'mv_dir', 'y', 'sign', '-']
        - ['callback_model_change_with_text_label', 'anchor', 'bottom','orientation','horizontal']
      3: 
        - ['callback_model_change_with_transformation', 'mv_dir', 'x', 'sign', '+']
        - ['callback_model_change_with_text_label', 'anchor', 'left','orientation','vertical']
      4: 
        - ['callback_model_change_with_transformation', 'mv_dir', 'x', 'sign', '-']
        - ['callback_model_change_with_text_label', 'anchor', 'right', 'orientation', 'vertical']
    callbacks_upon_leftmouse_click:
      1: null
      2: null
      3: null
      4: null      
  valve:
    shapes: ['circle.tiny*1', 'isocelesTriangle.type1*2']
    # shapes: ['rectangle.type1*1']
    ref_shape: null
    hide: [0]
    alignment:
      shapes: [[0,1],[0,2]]
      anchors: [['top','top'],['bottom','top']]
      gaps: [0.,0.]
      ref_anchors: [[null, null],[null, null]]
    transformation: 
      translate: [0,0]
    models: []
      # 0: sys/tg_test/1/boolean_scalar
      # 1: sys/tg_test/1/boolean_scalar
      # 2: sys/tg_test/1/boolean_scalar
    callbacks_upon_model_change:
      0: ['callback_model_change_with_text_label_on_off', 'anchor', 'top']
      1: ['callback_model_change_with_decoration_on_off']
      2: ['callback_model_change_with_decoration_on_off']
    callbacks_upon_leftmouse_click:
      0: null
      1: null
      2: null
  anchor:
    shapes: ['circle.tiny*2']
    ref_shape: null
    hide: [0, 1]
    alignment:
      shapes: [[0,1]]
      anchors: [['right','left']]
      gaps: [0.]
      ref_anchors: [[null, null]]
    transformation: 
      translate: [220,220]
    models: []
    callbacks_upon_model_change:
      1: []
      2: []
    callbacks_upon_leftmouse_click:
      1: null
      2: null
  label_eg:
    shapes: ['circle.tiny*1','rectangle.type2b*1']
    ref_shape: null
    hide: [0]
    alignment:
      shapes: [[0,1]]
      anchors: [['left','right']]
      gaps: [0.]
      ref_anchors: [[null, null]]
    transformation: 
      translate: [220,220]
    models: []
    callbacks_upon_model_change:
      1: []
      2: []
    callbacks_upon_leftmouse_click:
      1: null
      2: null      
viewers:
  viewer1:
    composites: ['anchor','valve', 'slit', 'slit', 'valve','slit','label_eg']
    transformation:
      translate:
        - [50, 220]
        - [220, 220]
        - [440, 220]
        - [660, 220]
        - [880, 220]
        - [1100, 220]
        - [1500, 220]
  viewer2:
    composites: ['valve','anchor']
    transformation:
      translate:
        - [100, 220]
        - [220, 220]